services:
  frases:
    image: frases
    container_name: frases
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8005
    restart: always
    ports:
      - 8005:8005
    networks:
      - frases-network
    volumes:
      - type: bind
        source: ./
        target: /app

networks:
  frases-network:
    driver: bridge
    name: frases-network
